version: '2'

services:
    mysqlbot:
        image: mariadb:10.1.22
        volumes:
            - /home/kai/linebot-jarvis/mysqlbot:/var/lib/mysql
            - /home/kai/jenkins-build/workspace/linebot_jarvis/bot/conf:/etc/mysql/my.cnf
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 09wfjvdedr09yopbn
            MYSQL_DATABASE: linebot
            MYSQL_USER: bot
            MYSQL_PASSWORD: yurabuai99
    bot:
        image: linebot
        volumes:
            - /home/kai/linebot-jarvis/butterha:/opt/butterha
        ports:
            - "443:443"
        restart: always
        depends_on:
            - mysqlbot
        links:
            - "mysqlbot:db"
