version: '2'

services:
    mysqlbot:
        image: mysql:5.6
        volumes:
            - ./mysqlbot/mysqlbot_data:/var/lib/mysql
            - ./bot/conf/my.cnf:/etc/mysql/my.cnf
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 09wfjvdedr09yopbn
            MYSQL_DATABASE: linebot
            MYSQL_USER: bot
            MYSQL_PASSWORD: yurabuai99
    bot:
        image: linebot
        #build: /home/kai/linebot-jarvis
        ports:
            - "443:443"
        restart: always
        depends_on:
            - mysqlbot
        links:
            - "mysqlbot:db"
